{% set name = "appscript" %}
{% set version = "1.1.2" %}
{% set sha256 = "15727bda6f4049be5436e1974461f96b088d14ad154950417a7cda04587e6097" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Mark-AEDeterminePermissionToAutomateTarget-extern-in.patch

build:
  number: 0
  skip: true  # [not osx]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  build:
    - {{ compiler('c') }}
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - aem
    - appscript
    - mactypes
    - osax
    - aem.ae
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://appscript.sourceforge.io/
  license: Public Domain
  summary: Control AppleScriptable applications from Python.
  description: |
    Appscript is a user-friendly Apple event bridge that allows users to
    control scriptable Mac OS X applications from Python, Ruby and Objective-C.
    Appscript makes these languages serious alternatives to Apple's own
    AppleScript language for automating your Mac.
  dev_url: https://svn.code.sf.net/p/appscript/code/py-appscript/
  doc_url: https://appscript.sourceforge.io/py-appscript/doc.html

extra:
  recipe-maintainers:
    - nehaljwani
