{% set name = "appscript" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 80943118bc97f9f78a8aa55f85565752ed4d82c7893427d7d9ebfdf401c12b2c

build:
  number: 0
  skip: true  # [not osx]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel

  run:
    - python
    - lxml >=4.7.1

test:
  imports:
    - aem
    - appscript
    - mactypes
    - osax
    - aem.ae
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/hhas/appscript
  license: LicenseRef-Public-Domain-with-PSF-exception
  license_family: Other
  license_file: README.rst
  summary: Control AppleScriptable applications from Python.
  description: |
    Appscript is a user-friendly Apple event bridge that allows users to
    control scriptable Mac OS X applications from Python, Ruby and Objective-C.
    Appscript makes these languages serious alternatives to Apple's own
    AppleScript language for automating your Mac.
  dev_url: https://pypi.org/project/appscript/
  doc_url: https://github.com/hhas/appscript

extra:
  recipe-maintainers:
    - nehaljwani
