travis:
  secure:
    BINSTAR_TOKEN: T4ytLRlkUe/7G6UHN5g342mjf0RMbg35PCmtWBrIxWGhtxwKx8YWfYigjtAkQ0Q/eBA4/NGcGMZ0BkTUbPrbzGgTjfxCjFwO9dnVsY6YAkIMPW3SSP1XW25bnMerO9fJEwmuU6MIqXTk/42BPvVy3KG5hq6bvso8lR0jn17IyewoOPrVToUwxmK+BP3k2kTiHXeXxpipk7WZozGdSNzUlNFkOYCG4mO3+b3mO723pSZk2mIr/C9VbQTtn6BpLBJ2094FPFg2uIQoWYy2F4Cv7ozE7jdLn4vvNiz+CJMCnUb+VxnI2OCg3jBkyoO5xFwkOtXpcVSFD4my2adBZWcO4R+9Y/DCOmwGvJ83zMM/r+G5/TbX+3toAZ4Q7ukRa0L1JGw7uNRh7wbnwY0Z9JJa7JZU7yK2ivbaADwSp2vxvf81C0kCxoBj7IAaSZ1xN40L/cPAVMrjuBHvANr7keen4Y6iWFb2XcFrcGStALjawOJnWfjs9GTDcDd+FCfLe62eVGa/I4i5RMwC/vyDDPk+sA9XcTttg+j81u6mBVLd4g7oZypfUzGChrJ/phsmCHuIdWAaYtKacZRv48sbNBaevgLZTCJS74jemCi6Cocy7A3nFstcvgNtQq8/JXlWxcX+8/GfS++exHL8sE7CFqfiAVSQj8HvpedgB+pg5dIL8O0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
