travis:
  secure:
    BINSTAR_TOKEN: fYHGznS3lQGMlHTmpzREQdTZihztbZcjIu/Wt3d8Xh3O+TwRM5K9Fh/A/RQ4Tfpp7zTGHWTDOtoBu+3lZDDucH3DkknuxCGU/c7mbyyEhDs2vt2PLMuIasZ0Ip0lS1K1I6gp4nQtGsMGP8j5P82y2rIEJ5GS9F0Lk9APjnlWcD2uRtC+tlF1RAfDmNX9WsuKodzuc5Y+P9cv4f22YpXDRp1KjcYlA7uC94i5kpI3p/CKB1Xynj8wIDLL8U1sTwmiHUd+00FeAyBfXK7K/x1nDJgfzEUrJBg4xu9cDpS43ePuAgdXQd2yOIszcImeHo9lLKSlWl6eCbElvBeRqsL+oScqke7gtCeQ3Xdh0+p589iHkU8ztek0nY2ZivlYxDLJBe+bIcowtpXcSsZ3wJRfgc6WtACoRvg9h9AihLAd6EWfbBSENAri5+NVicNsxFvNzMbT/e1uFGsRefg/uxar7JFS+NPZx//H+PTEMk3Hr2dkszhjupPMJ7XDzpa3ViO58LNHnsW3EI4bSw1fhA85rV3gxiUIeNbXbuD71ij3c2qY2Vs3GF/IFNfar1k4SHbNG0r3iGq/F1w883R6peByCR2Ly+njphFRroIOMmTq1Levmp2A6ho7u/QxID9udXiZNUBbx7Wc6cFX+j3pPBWxWEL2YTBC+IZroE0csqyCN/A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
